
-- Seed portfolios
INSERT INTO public.portfolios (title, slug, category, district, short_description, description, cover_image_url, gallery_urls, impact_summary, beneficiaries, budget_spent, completed_date, is_featured, is_published, order_index) VALUES
('Rural Classroom Renovation', 'rural-classroom-renovation', 'Education', 'Rangpur', 'Renovated 12 primary school classrooms with books, benches and clean toilets across 3 unions.', E'Across three remote unions of Rangpur, twelve government primary school classrooms were renovated from June to October 2025. New benches, blackboards, fans and a fresh paint job replaced decades-old infrastructure.\n\nAlongside the physical upgrade, every student received a fresh set of textbooks, notebooks and a hygiene kit. Local teachers were trained on a child-friendly learning approach in partnership with district education officers.\n\nThe project was completed within budget and inaugurated by the community in November 2025.', '/img/portfolio-education.jpg', ARRAY['/img/portfolio-education.jpg','/img/portfolio-women.jpg']::text[], '1,200+ children back in dignified classrooms across 12 schools.', 1240, 1850000, '2025-11-12', true, true, 100),

('Jamuna Flood Emergency Response', 'jamuna-flood-relief', 'Emergency', 'Sirajganj', '72-hour rapid relief — dry food, medicine and clean water for 3,800 flood-affected families.', E'When Jamuna river crossed danger level in August 2025, Qudrat Foundation volunteers deployed within 24 hours. Boats loaded with dry food packets, ORS, water purification tablets and emergency medicines reached 22 chars and remote villages.\n\nOver a 72-hour window, 3,800 families received complete relief packages. A mobile medical camp treated 410 patients on-site, with critical cases referred to Sirajganj Sadar Hospital.\n\nPost-flood, the team continued with shelter repair grants for 180 worst-affected households.', '/img/portfolio-flood.jpg', ARRAY['/img/portfolio-flood.jpg']::text[], '3,800 families fed and 410 patients treated within 72 hours.', 3800, 4200000, '2025-08-30', true, true, 90),

('Free Health Camp — Bhola', 'bhola-health-camp', 'Health', 'Bhola', '3-day mobile medical camp in coastal Bhola serving elderly and women patients.', E'A three-day mobile health camp was organised in two coastal upazilas of Bhola in partnership with five volunteer doctors from Dhaka Medical College.\n\nFree consultation, blood pressure and diabetes screening, basic medicine, and women''s health checkups were provided to over 900 patients. 47 cases requiring surgery were sponsored by the Foundation.', '/img/portfolio-health.jpg', ARRAY['/img/portfolio-health.jpg']::text[], '900+ patients treated; 47 surgeries sponsored.', 947, 950000, '2025-09-18', false, true, 80),

('Women Entrepreneurs — Sewing Centre', 'women-sewing-centre', 'Livelihood', 'Khulna', 'Set up a sewing training centre and seeded 40 women with sewing machines and start-up capital.', E'In partnership with a local women''s cooperative, a six-month sewing and tailoring training program was completed for 60 women in rural Khulna. Forty graduates received their own sewing machines and BDT 8,000 each in start-up capital.\n\nSix months later, 34 of them report a steady monthly income of BDT 6,000-9,000 from tailoring orders.', '/img/portfolio-women.jpg', ARRAY['/img/portfolio-women.jpg']::text[], '40 women earning independent income within 6 months.', 60, 1250000, '2025-07-05', true, true, 70),

('Safe Water for 8 Villages', 'safe-water-8-villages', 'Water', 'Satkhira', 'Installed 22 arsenic-free deep tubewells across 8 villages in coastal Satkhira.', E'Coastal Satkhira faces both salinity and arsenic contamination. The Foundation installed 22 deep tubewells with arsenic-removal filters, ensuring safe drinking water for approximately 6,500 villagers across 8 villages.\n\nA local water-committee was formed in each village for long-term maintenance, with one-year free service support from the installer.', '/img/portfolio-water.jpg', ARRAY['/img/portfolio-water.jpg']::text[], '6,500 villagers with year-round safe water access.', 6500, 2400000, '2025-05-22', false, true, 60),

('Winter Blanket Drive 2024', 'winter-blanket-drive-2024', 'Relief', 'Nilphamari', 'Distributed 5,200 warm blankets across northern Bangladesh during the 2024 cold wave.', E'During the January 2024 cold wave that killed over 30 people in northern Bangladesh, Qudrat Foundation distributed 5,200 warm wool blankets in Nilphamari, Panchagarh and Kurigram. Priority was given to elderly, disabled people and street-dwellers.\n\nThe entire drive was funded by 1,400+ small donors and completed in 11 days.', '/img/portfolio-winter.jpg', ARRAY['/img/portfolio-winter.jpg']::text[], '5,200 blankets across 3 northern districts in 11 days.', 5200, 1560000, '2024-02-02', false, true, 50);

-- Update existing project image URLs
UPDATE public.projects SET image_url = '/img/portfolio-winter.jpg' WHERE slug = 'winter-relief-2024';
UPDATE public.projects SET image_url = '/img/portfolio-women.jpg' WHERE slug = 'sustainable-seeds-program';
UPDATE public.projects SET image_url = '/img/portfolio-water.jpg' WHERE slug = 'sylhet-safe-water';
UPDATE public.projects SET image_url = '/img/portfolio-education.jpg' WHERE slug = 'digital-classroom';
